CREATE TYPE "public"."field_type" AS ENUM('number', 'string', 'boolean', 'enum');--> statement-breakpoint
CREATE TYPE "public"."ui_lib" AS ENUM('Ant', 'ShadCN', 'MUI');--> statement-breakpoint
CREATE TABLE "authors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "authors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"author_name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	CONSTRAINT "authors_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "components" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "components_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"ui_lib" "ui_lib" DEFAULT 'Ant',
	"ui_lib_ver" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "crud_modules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "crud_modules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"module_name" varchar(255) NOT NULL,
	"user_id" integer
);
--> statement-breakpoint
CREATE TABLE "fields" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fields_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"field_name" varchar(255) NOT NULL,
	"field_type" "field_type" NOT NULL,
	"nullable" boolean DEFAULT true,
	"unit" boolean DEFAULT false,
	"module_id" integer
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_name" varchar(255),
	"email" varchar(255) NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "crud_modules" ADD CONSTRAINT "crud_modules_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "fields" ADD CONSTRAINT "fields_module_id_crud_modules_id_fk" FOREIGN KEY ("module_id") REFERENCES "public"."crud_modules"("id") ON DELETE cascade ON UPDATE cascade;